"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { BookOpen, Loader2, FlaskConical, Download } from "lucide-react";
import { api } from "@/lib/api";

interface Experiment {
  name: string;
  hypothesis: string;
  methodology: string;
  expected_outcome: string;
  baseline: string;
  metrics: string[];
  estimated_duration: string;
}

interface Dissertation {
  research_title: string;
  research_questions: string[];
  hypotheses: string[];
  methodology: string;
  experiments: Experiment[];
  theoretical_framework: string;
  contribution_to_knowledge: string;
  expert_validation_plan: string[];
  publication_targets: string[];
  ethical_considerations: string;
  timeline_months: number;
  chapter_outline: string[];
}

interface Props {
  analysisId: string;
  dissertationContribution?: string;
}

function RQBadge({ index }: { index: number }) {
  return (
    <span className="shrink-0 rounded-full border border-violet-400/30 bg-violet-400/10 px-2.5 py-1 text-[11px] font-bold text-violet-300">
      RQ{index + 1}
    </span>
  );
}

function HBadge({ label }: { label: string }) {
  return (
    <span className="shrink-0 rounded-full border border-purple-400/30 bg-purple-400/10 px-2.5 py-1 text-[11px] font-bold text-purple-300">
      {label}
    </span>
  );
}

export function DissertationPanel({ analysisId, dissertationContribution }: Props) {
  const [dissertation, setDissertation] = useState<Dissertation | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await api.post(`/api/v1/dissertation/scaffold/${analysisId}`);
      setDissertation(res.data.dissertation as Dissertation);
    } catch (err: any) {
      setError(err?.response?.data?.message || "Failed to generate dissertation framework.");
    } finally {
      setLoading(false);
    }
  }

  function exportLatex() {
    if (!dissertation) return;
    const latex = `% ${dissertation.research_title}
% Generated by ASIS v4.0

\\documentclass[12pt]{report}
\\usepackage{geometry}
\\geometry{a4paper, margin=2.5cm}

\\title{${dissertation.research_title}}
\\date{\\today}

\\begin{document}
\\maketitle

\\chapter{Introduction}

\\section{Research Questions}
${dissertation.research_questions.map((rq, i) => `\\item[${i + 1}.] ${rq}`).join('\n')}

\\section{Hypotheses}
${dissertation.hypotheses.map((h, i) => `H${i + 1}: ${h}`).join('\n\n')}

\\section{Theoretical Framework}
${dissertation.theoretical_framework}

\\chapter{Methodology}
${dissertation.methodology}

\\chapter{Experiments}
${dissertation.experiments.map(e => `\\section{${e.name}}\n${e.methodology}\n\\textbf{Expected Outcome:} ${e.expected_outcome}`).join('\n\n')}

\\chapter{Conclusion}
${dissertation.contribution_to_knowledge}

\\end{document}`;

    const blob = new Blob([latex], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'dissertation-framework.tex';
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: 0.1 }}
      className="rounded-3xl border border-violet-400/10 bg-[#0a080f] p-5"
    >
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <BookOpen size={16} className="text-violet-400" />
            <h2 className="text-lg font-semibold text-slate-50">Dissertation Readiness</h2>
          </div>
          <p className="mt-1 text-sm text-slate-400">
            Research questions, hypotheses, experiments, expert validation plan.
          </p>
          {dissertationContribution && (
            <p className="mt-2 rounded-2xl border border-violet-400/20 bg-violet-400/10 px-3 py-2 text-xs italic text-violet-200">
              &ldquo;{dissertationContribution}&rdquo;
            </p>
          )}
        </div>
        <div className="flex gap-2">
          {dissertation && (
            <button
              onClick={exportLatex}
              className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold text-slate-300 transition hover:bg-white/10"
            >
              <Download size={13} /> Export LaTeX
            </button>
          )}
          {!dissertation && (
            <button
              onClick={generate}
              disabled={loading}
              className="inline-flex items-center gap-2 rounded-full border border-violet-400/30 bg-violet-400/10 px-4 py-2 text-sm font-semibold text-violet-200 transition hover:bg-violet-400/20 disabled:opacity-50"
            >
              {loading ? <Loader2 size={14} className="animate-spin" /> : <FlaskConical size={14} />}
              {loading ? "Scaffolding framework..." : "Generate Research Framework"}
            </button>
          )}
        </div>
      </div>

      {error && (
        <div className="mt-4 rounded-2xl border border-rose-400/20 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</div>
      )}

      <AnimatePresence>
        {dissertation && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="mt-5 space-y-5"
          >
            <h3 className="text-xl font-semibold leading-tight text-slate-50">{dissertation.research_title}</h3>

            {/* Research Questions */}
            <div>
              <div className="mb-3 text-[11px] uppercase tracking-widest text-violet-300">Research Questions</div>
              <div className="space-y-2">
                {dissertation.research_questions.map((rq, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.03] px-4 py-3"
                  >
                    <RQBadge index={i} />
                    <span className="text-sm leading-6 text-slate-200">{rq}</span>
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Hypotheses */}
            <div>
              <div className="mb-3 text-[11px] uppercase tracking-widest text-purple-300">Hypotheses</div>
              <div className="space-y-2">
                {dissertation.hypotheses.map((h, i) => (
                  <div key={i} className="flex items-start gap-3 rounded-2xl border border-purple-400/10 bg-purple-400/5 px-4 py-3">
                    <HBadge label={`H${i + 1}`} />
                    <span className="text-sm leading-6 text-slate-300">{h}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Experiments */}
            <div>
              <div className="mb-3 text-[11px] uppercase tracking-widest text-slate-400">Experiments</div>
              <div className="space-y-3">
                {dissertation.experiments.map((exp, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, y: 8 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.2 + i * 0.1 }}
                    className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"
                  >
                    <div className="mb-2 flex items-center gap-2">
                      <FlaskConical size={13} className="text-violet-400" />
                      <span className="text-sm font-semibold text-slate-100">{exp.name}</span>
                      <span className="rounded-full border border-purple-400/20 bg-purple-400/10 px-2 py-0.5 text-[10px] text-purple-300">{exp.hypothesis}</span>
                      {exp.estimated_duration && (
                        <span className="text-[10px] text-slate-500">{exp.estimated_duration}</span>
                      )}
                    </div>
                    <div className="grid gap-2 text-xs text-slate-400 sm:grid-cols-2">
                      <div><span className="text-slate-500">Method:</span> {exp.methodology}</div>
                      <div><span className="text-slate-500">Expected:</span> {exp.expected_outcome}</div>
                      <div><span className="text-slate-500">Baseline:</span> {exp.baseline}</div>
                      {exp.metrics?.length > 0 && (
                        <div><span className="text-slate-500">Metrics:</span> {exp.metrics.join(', ')}</div>
                      )}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Expert Validation + Publications */}
            <div className="grid gap-4 xl:grid-cols-2">
              <div>
                <div className="mb-2 text-[11px] uppercase tracking-widest text-slate-400">Expert Validation Plan</div>
                <div className="space-y-1">
                  {dissertation.expert_validation_plan?.map((e, i) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-slate-300">
                      <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-violet-400" />
                      {e}
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <div className="mb-2 text-[11px] uppercase tracking-widest text-slate-400">Publication Targets</div>
                <div className="space-y-1">
                  {dissertation.publication_targets?.map((p, i) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-slate-300">
                      <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-purple-400" />
                      {p}
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-xs text-slate-400">
              <span className="text-slate-500">Contribution: </span>{dissertation.contribution_to_knowledge}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
