steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - asis/backend/Dockerfile
      - -t
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_BACKEND_IMAGE}:${SHORT_SHA}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_BACKEND_IMAGE}:${SHORT_SHA}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_BACKEND_IMAGE}:${SHORT_SHA}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - "8000"

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: asis
  _BACKEND_IMAGE: asis-backend
  _BACKEND_SERVICE: asis-backend
  _REGION: us-central1

